# Generated by Django 3.1 on 2020-08-27 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0002_auto_20200827_1851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Painting',
            new_name='AbstractPainting',
        ),
    ]
