# Generated by Django 3.1 on 2020-08-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0004_acrylicpainting'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastelPainting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('artist', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
